---
# general details about our VPC
vpc_name: techchallenge-vpc
vpc_key: techchallenge-key
vpc_dns_zone: techchallenge

# IP CIDR block for the VPC
vpc_cidr_block: 10.0.0.0/16

# conf.toml setttings
DbUser: postgres
DbPassword: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33663637353036376561353439663333313130363364386362356339373432613638613631396431
          6430613835353533616336353232623630366536383637370a323665663866626165326537353263
          33646439633335613563636365623136613539303264313363306439653763303637316437356461
          3766636665333936630a376139616537633634306338346561313739353834343734643561396337
          3938
DbName: techchallengeappdb
DbPort: 5432
ListenHost: 0.0.0.0
ListenPort: 3000
# External port number to access the app through
external_port: 80

# credentials for AWS (encrypted useing a value key)
aws_region: ap-southeast-2
aws_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65616530333031313330333631646235353434363962393763333263366431303065383338396430
          3463633365333764613331386332626666383966383230620a373333633761613337323336353962
          32386532646166383562396136303261643164343136383535643262346632646233353764646363
          6431366230363432340a326337383932366334353266333234663366656263646232663362643430
          61373962366664373365663137386362623664336539663461323731663233646262
aws_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323835666339326436303263613635643232653232363732346461656363646261626231616236
          3736346537666562656333643231373336376433646365650a333562386335376462613436376634
          35643832643938353632333937373739353565333433336231663262663338363561313566643361
          6262646466386630320a363063373832306465336334326364386239333737663061323139356266
          62633934343836336462326466663962333935656533373838363738393535353739383235396433
          3464383933616165383530386237366363616339666332373962